// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7EiOWlSj1cy8E_LX6OQ2sdA_lLpMfao',
    appId: '1:699614750464:android:df66f5c8d988ec5e1fb5e5',
    messagingSenderId: '699614750464',
    projectId: 'praclog-6f18f',
    storageBucket: 'praclog-6f18f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCo4nRlmfWgNSS9LeK-6rTgyl7vj5eos',
    appId: '1:699614750464:ios:c1fe0471bd1d81f51fb5e5',
    messagingSenderId: '699614750464',
    projectId: 'praclog-6f18f',
    storageBucket: 'praclog-6f18f.appspot.com',
    androidClientId: '699614750464-1mtbfqi3teelmldulqu6dank0slt5lt3.apps.googleusercontent.com',
    iosClientId: '699614750464-jd85iaulb8v2vug9ir4hkpndttcdudd7.apps.googleusercontent.com',
    iosBundleId: 'com.psycformusos.praclog',
  );
}
