// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntk1jBHpa0ir2gDcKwKGBYiGB3eARoAQ',
    appId: '1:60305170884:android:b58f27d59818c57dff0491',
    messagingSenderId: '60305170884',
    projectId: 'praclog-b31bd',
    storageBucket: 'praclog-b31bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA200aIl6Bu1v3C2TBnuqJy58CaSN3n2OA',
    appId: '1:60305170884:ios:408d3a99bb1dd0c6ff0491',
    messagingSenderId: '60305170884',
    projectId: 'praclog-b31bd',
    storageBucket: 'praclog-b31bd.appspot.com',
    androidClientId: '60305170884-18v1sub9urbgj772rj0h623qp71aqab6.apps.googleusercontent.com',
    iosClientId: '60305170884-ohq1v3lb9jdc18hl8aj8n0fakotu9l7h.apps.googleusercontent.com',
    iosBundleId: 'com.psycformusos.praclog.dev',
  );
}
